### ISSUE TITLE
Cant use Poser

### ISSUE THREAD

**Issue by MritulaC** [mzolfaghari/3D-human-pose-estimation#1]
Hi,
 Im trying to generate 3D jopint points for humans in my videos. Im trying to use 3D-human-pose-estimation of yours. You have mentiones to user Poser which Im not able to find. Can you kindly help?

Thanks,
 Mritula

**Comment by mzolfaghari** [comment]
Hi Mritula,

You can find the software in the following link:
https://my.smithmicro.com/poser-3d-animation-software.html?

Best,
